---

- name: task 3.2
  hosts: r1
  gather_facts: false

  tasks:

    - name: Config ACL
      ios_config:
        before:
          - interface GigabitEthernet0/1
          - no ip access-group INET-to_LAN in
          - exit 
          - no ip access-list extended INET-to-LAN
        parents:
          - ip access-list extended INET-to_LAN
        lines:
          - permit tcp 10.0.1.0 0.0.0.255 any eq www
          - permit tcp 10.0.1.0 0.0.0.255 any eq 22
          - permit icmp any any
          - permit tcp 10.0.1.0 0.0.0.255 any eq telnet
        after:
          - interface GigabitEthernet0/1
          - ip access-group INET-to-LAN in





