---

- name: task 3.1
  hosts: cisco_routers
  gather_facts: false

  tasks:

    - name: Config line vty
      ios_command:
        commands: sh arp
      register: sh_arp_output

    - name: Show Arp
      debug: var=sh_arp_output.stdout_lines
