---

- name: Run cfg commands on router
  hosts: 192.168.1.33

  tasks:

    - name: Config interface
      ios_config:
        parents:
          - interface GigabitEthernet0/3
        lines:
          - ip address 192.168.130.2 255.255.255.0
        after:
          - no shutdown