- name: Run show commands on routers
  hosts: all

  tasks:
    - name: Get interfaces info
      cli_command:
        command: "{{ interfaces_info }}"
      register: command_output

    - name: Debug registred var
      debug:
        var: command_output.stdout_lines
