- name: Run show commands on routers
  hosts: all

  tasks:
    - name: Clear interface counters
      cli_command:
        command: clear counters gi0/0
        prompt: 'Clear "show interface" counters on this interface'
        answer: y


    - name: Clear interface counters in loop
      cli_command:
        command: clear counters {{ item }}
        prompt: 'Clear "show interface" counters on this interface'
        answer: y
      loop: [gi0/0, gi0/1, gi0/2]


    - name: Send commands
      cli_command:
        command: "{{ item }}"
      loop: [sh ip int br, show clock]
